//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatBrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationCategory
    {
        public EducationCategory()
        {
            this.AgeGroups = new HashSet<AgeGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string Age { get; set; }
        public string AgeEn { get; set; }
        public int SortOrder { get; set; }
        public int EducationCountryId { get; set; }
    
        public virtual EducationCountry EducationCountry { get; set; }
        public virtual ICollection<AgeGroup> AgeGroups { get; set; }
    }
}
